default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  username: postgres
  password: password

development:
  <<: *default
  database: actioncable_development

test:
  <<: *default
  database: actioncable_development

production:
  <<: *default
  database: actioncable_development
